### ISSUE TITLE
Filling in SyncedLogViewer MDOA track changes with zoom level

### ISSUE THREAD

**Issue by Midtveit** [equinor/webviz-subsurface-components#1017]
Zoomed out the filling looks correct.
![image](https://user-images.githubusercontent.com/42234769/170029824-7cbe3cd0-4708-4e1b-83ea-e6fa9a8fa3fc.png)

Zooming in makes filling get a stripe see picture below.
And filling changes with zoom level
![image](https://user-images.githubusercontent.com/42234769/170030092-c0bfc1d4-13dc-4a82-a7c0-7efccb45fe48.png)

**Comment by Vladimir-Kokin** [comment]
It also can be reproduced in WellLogViewer Default story when TVD primary scale is used
![изображение](https://user-images.githubusercontent.com/86053741/170101865-9a3cbe5c-e10a-4eaf-88cb-d2f443c18b85.png)

**Comment by shadab-skhan** [comment]
Waiting for response from Videx team
