### ISSUE TITLE
 [BUG] Hardcoded colorTables file in emerson-eps/color-tables components which cannot be changed with props

### ISSUE THREAD

**Issue by Vladimir-Kokin** [equinor/webviz-subsurface-components#1019]
_colorTables_ are hardcoded in the files:
react-app\src\component\Utils\legendCommonFunction.ts
react-app\src\component\ColorSelector\ColorSelectorWrapper.tsx
color-tables\react-app\src\component\Legend\ContinuousLegend.tsx 
color-tables\react-app\src\component\Legend\DiscreteLegend.tsx 
`import colorTables from "../color-tables.json";`

Additionally DiscreteLegend from **emerson-eps/color-tables** version 0.2.30 (currently used in **webviz-subsurface-components**)  has a bug which does not allow change _colorTables_ via prop because it was missed from
`export const DiscreteColorLegend: React.FC<colorLegendProps> = ({`
function parameters

In the current version of **emerson-eps/color-tables**
`colorTables: colorTablesArray | string;`
was completely removed from _type colorLegendProps_ so _colorTables_ remains always with hardcoded values

See also https://github.com/emerson-eps/color-tables/issues/153

**Comment by shruthirai** [comment]
Fixed
