### ISSUE TITLE
DeckGL well names in "WellsLayer" are not displayed

### ISSUE THREAD

**Issue by ElfarriBadr** [equinor/webviz-subsurface-components#1028]
Well names in @@type : "WellsLayer" are not displayed on the map and are not either available as a toggling option to be turned on and off. Same data used in Storybook as an input for wellsLayer is used to test in python component. There are no names visual on the map.

**Comment by hkfb** [comment]
@shadab-skhan there is support for well labels in the map, maybe we should create a storybook example?

**Comment by ElfarriBadr** [comment]
The storybook already includes an example with well labels, the bug is related to python DeckGl component. I am not getting the same result in python as in the storybook using the same data and configuration of the WellsLayer. The label name option is missing and the labels are not visible. i guess something wrong with python webviz_subsurface_components DeckGLMap component in python.

**Comment by ElfarriBadr** [comment]
Test with the newest version, seems to be working ok, closing this issue
