### ISSUE TITLE
When having multiple `ColormapLayer`, changing the `valueRange` in one layer updates the range in all the layers

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1029]
To reproduce:
https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/deckglmap--multi-color-map
Change the valueRange in one of the layers and observe that the valueRange is updated in both layers.

**Comment by shruthirai** [comment]
Fixed by https://github.com/equinor/webviz-subsurface-components/pull/1036
