### ISSUE TITLE
Allow initialization of `DeckGLMap` without specifying bounds

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1031]
E.g. by having some defaultProps specified for bounds.

Use cases
- [x] Start with an empty map without specifying bounds.
- [x] Adding layers to existing map and keeping existing camera position
- [x] Adding layers to existing map and refocus camera on new project bounds

Suggestion: make `bounds` optional. If not defined, auto-calculate bounds.

**Comment by nilscb** [comment]
This works now. 
If bounds is not set and adding a layer, the camera will reset to look at the middle of the combined data.

If bounds is set and a new layer is added, the camera will stay fixed (at the bounds)
