### ISSUE TITLE
Spacing between axis labels

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#1053]
Axis labels appear too close to each other to be legible.

![Screenshot from 2022-06-14 19-19-02](https://user-images.githubusercontent.com/19621822/173638561-0d35c773-61fe-44b9-adaf-ebc214b98ed0.png)

**Comment by shadab-skhan** [comment]
Maybe related #897

**Comment by nilscb** [comment]
This works much better now. It was rewritten to show fewer labels are shown depending on available space. It may never be 100% though. Unless one implements some kind of collision detection algorithm between labels. Suggest to close this issue
