### ISSUE TITLE
colorName prop in DeckGLMap only affects legend and not the map itself

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1094]
In webviz-subsurface-components storybook, in story color-map-layer-color-selector, selecting a different color map only affects the legend and not the map itself.
![image](https://user-images.githubusercontent.com/18436935/176380823-474de0e2-0945-4b27-a272-fac09e0e7f89.png)

**Comment by shadab-skhan** [comment]
In this example colorName is not a required prop, this should be removed as the color scale can be changed from the colorSelector.

ColorName prop is provided to colorSelector component to set default/initial color scale, which the component should have taken care. This example needs refactoring!
