### ISSUE TITLE
Show well picks in Correlation-view

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#1096]
- [X] Show lines for well picks for correlation-view, across several wells
- [X] Show lines in color according to pick name 
- [x] Show fill color between pick lines in the area between wells (like RMS)
- [x] Add Depth label in its depth tracks for MD and TVD.
- [x] Allow flattening on one (1) well pick 
- [x] Make the width between wells customizable , individual with specified between each pair of wells
- [x] Fill color and/or patterns in welllog view
- [x] Show fillpattern between pick lines in the area between wells (like RMS)
- [x] Allow flattening on 2 well picks

**Comment by hkfb** [comment]
See also https://github.com/equinor/webviz-subsurface-components/issues/1051

**Comment by hkfb** [comment]
@Midtveit @Vladimir-Kokin @HansKallekleiv @shadab-skhan @nilscb any thoughts about data format for well picks?

Do we have well picks in RoxarAPI, and what is the data format there?

**Comment by HansKallekleiv** [comment]
We are using wellpicks in webviz  for the deckglmap.
Example on format we chose and script to extract with roxar api here: https://github.com/equinor/webviz-subsurface-testdata/tree/master/observed_data%2Fdrogon_well_picks

**Comment by Vladimir-Kokin** [comment]
@hkfb It seems #1348 should close this issue (last check in issue description)
![изображение](https://github.com/equinor/webviz-subsurface-components/assets/86053741/fe763939-e999-43f2-bb2b-ffc0948f69a7)
