### ISSUE TITLE
Support separate tooltips for Well heads and Well trajectories

### ISSUE THREAD

**Issue by rtaragan** [equinor/webviz-subsurface-components#1129]
Currently, when hovering over well heads and well trajectories they are being highlighted separately, this is good. 
We want that when hovering over them, a different tooltip will be presented for heads and trajectories and that the tooltips will show different information for each object type.

**Comment by shadab-skhan** [comment]
In the PR we have created a story for separate wellhead and trajectory info: https://github.com/equinor/webviz-subsurface-components/pull/1135

It's possible to show different information in both the object based on info.featureType property example is [shown here](https://github.com/equinor/webviz-subsurface-components/pull/1135/files#diff-d76884169969a6695e2d94cda203c06c85c3338128be82eb004d42d3412d836d)
