### ISSUE TITLE
DeckGL component does not zoom to bounds on callback

### ISSUE THREAD

**Issue by oysteinequinor** [equinor/webviz-subsurface-components#1157]
I am trying to change the viewport of the deckgl component in a callback so that my polygon is zoomed and centered.
Initializing the component with bounds allows me to define the exact viewport I want, but this is not the case when using the callback.

By adding a callback to the bounds and setting them as I would for the initialization, the DeckGL component centers the view on my bounds, but does not change the zoom.
This results in either not seeing my entire bounds, or seeing much more than my bounds intended.

Minimal example:

Expected:
Map is zoomed out about 20%.

Actual:
Nothing happens.

```
import time

import dash
import requests
import webviz_subsurface_components


app = dash.Dash(__name__)
test_data = requests.get(
    "https://raw.githubusercontent.com/equinor/webviz-subsurface-components/master/react/src/demo/example-data/deckgl-map.json"
).json()[0]
app.layout = webviz_subsurface_components.DeckGLMap(**test_data)


@app.callback(
    dash.Output(component_id=test_data["id"], component_property="bounds"),
    dash.Input(component_id=test_data["id"], component_property="bounds"),
)
def zoom_out(_):
    b = [432205, 6475078, 437720, 6481113]  # test_data["bounds"]
    i = 1000  # zoom level ~0.8
    time.sleep(5)  # Wait so we can see the change
    print("Map should zoom out now")
    return [
        b[0] - i,
        b[1] - i,
        b[2] + i,
        b[3] + i,
    ]


app.run_server()
```

**Comment by oysteinequinor** [comment]
This is still an issue for us and makes our app look a bit weird. :) Do you have an estimate for when this might be done?

**Comment by shadab-skhan** [comment]
> This is still an issue for us and makes our app look a bit weird. :) Do you have an estimate for when this might be done?

Hi, I am investigating the issue, will keep you posted.
