### ISSUE TITLE
issues to run the examples

### ISSUE THREAD

**Issue by miroine** [equinor/webviz-subsurface-components#116]
hei i was trying to run the example_hm.py but than got some errors on the module ?
(py3_venv) miroine@Merouanes-MacBook-Air webviz-subsurface-components % pip install webviz_subsurface_components             
Requirement already satisfied: webviz_subsurface_components in /Users/miroine/envs/py3_venv/lib/python3.7/site-packages (0.0.25)
Requirement already satisfied: dash~=1.6 in /Users/miroine/envs/py3_venv/lib/python3.7/site-packages (from webviz_subsurface_components) (1.9.1)
Requirement already satisfied: dash-core-components==1.8.1 in /Users/miroine/envs/py3_venv/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (1.8.1)
Requirement already satisfied: Flask>=1.0.2 in /usr/local/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (1.1.1)
Requirement already satisfied: dash-html-components==1.0.2 in /Users/miroine/envs/py3_venv/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (1.0.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (4.2.1)
Requirement already satisfied: dash-table==4.6.1 in /Users/miroine/envs/py3_venv/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (4.6.1)
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (0.17.1)
Requirement already satisfied: dash-renderer==1.2.4 in /Users/miroine/envs/py3_venv/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (1.2.4)
Requirement already satisfied: flask-compress in /usr/local/lib/python3.7/site-packages (from dash~=1.6->webviz_subsurface_components) (1.4.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.7/site-packages (from Flask>=1.0.2->dash~=1.6->webviz_subsurface_components) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.7/site-packages (from Flask>=1.0.2->dash~=1.6->webviz_subsurface_components) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.7/site-packages (from Flask>=1.0.2->dash~=1.6->webviz_subsurface_components) (0.15.5)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.7/site-packages (from Flask>=1.0.2->dash~=1.6->webviz_subsurface_components) (2.10.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from plotly->dash~=1.6->webviz_subsurface_components) (1.12.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/site-packages (from plotly->dash~=1.6->webviz_subsurface_components) (1.3.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask>=1.0.2->dash~=1.6->webviz_subsurface_components) (1.1.1)
(py3_venv) miroine@Merouanes-MacBook-Air webviz-subsurface-components % python examples/example_hm.py 
Traceback (most recent call last):
  File "examples/example_hm.py", line 9, in <module>
    import webviz_subsurface_components
  File "/Users/miroine/project_developments/repos/webviz-subsurface-components/webviz_subsurface_components/__init__.py", line 12, in <module>
    from ._imports_ import *
ModuleNotFoundError: No module named 'webviz_subsurface_components._imports_'

**Comment by anders-kiaer** [comment]
Hi @miroine. 

Looking at the traceback, it looks like `import webviz_subsurface_components` goes to the folder `/Users/miroine/project_developments/repos/webviz-subsurface-components/webviz_subsurface_components/init.py`, which I guess might be a local clone of this repository?

Note that if you are cloning the repository yourself, and use that in your Python environment instead of a pure `pip install webviz_subsurface_components` from PyPI, you will need to build the JavaScript library yourself first, e.g. something like:
```bash
npm ci --ignore-scripts
npm run postinstall
npm run build
pip install -e .
```
If you are not developing the JavaScript library shipped with `webviz_subsurface_components` yourself, the easiest approach is to make sure your Python environment uses what comes from a `pip install webviz_subsurface_components` from PyPI.

**Comment by miroine** [comment]
ok now I got it ... thanks u are the man
