### ISSUE TITLE
[NGRM] - Interpolation by corner cells needs improving

### ISSUE THREAD

**Issue by vardit123y** [equinor/webviz-subsurface-components#1160]
Webviz image
![Webviz-LH-RH](https://user-images.githubusercontent.com/108064745/187399542-8f95f4f8-c0dc-44bb-83b0-7edf1de41d2b.PNG)

as a good reference, this is how the same data looks in SKUA:
SKUA image
![SKUA-LH-RH](https://user-images.githubusercontent.com/108064745/187399788-4f5e3f54-c6c2-44fd-9f35-37830dee1014.png)

**Comment by anders-kiaer** [comment]
Thanks for the report @vardit123y. Are these images using open data sets such that you can upload the images here on GitHub? I'm not able to see them - looks like these are links to sharepoint (behind authentication).

**Comment by nilscb** [comment]
It would be nice to have the setup and input data for debugging this. I will need the depth data and the properties data. That is the files refered to by the "meshUrl" property and the "propertiesUrl" property. And preferable also the "frame" property.
