### ISSUE TITLE
Change the default rotation center for 3D view

### ISSUE THREAD

**Issue by mmatselinskiy** [equinor/webviz-subsurface-components#1172]
By default, it seems that the 3D rotation is implemented based around a point of zero depth. This needs to be changed to the center of the rotation block - i.e., center of the opened map.
![WebVizRotationCenter1](https://user-images.githubusercontent.com/110110850/186641826-a469a8a3-c7f7-4bee-b9ec-9760868b0d41.gif)

**Comment by shadab-skhan** [comment]
See also #867
