### ISSUE TITLE
[NGRM] - Interpolation by center cells - missing cells

### ISSUE THREAD

**Issue by vardit123y** [equinor/webviz-subsurface-components#1176]
In some cases there are missing cells:
![image](https://user-images.githubusercontent.com/108064745/187401913-96b364db-39f1-4778-be61-ebd46ccdc75a.png)

The image with corner interpolation looks like this:
![Webviz-LH-RH](https://user-images.githubusercontent.com/108064745/187402024-57a97008-aa52-4834-9d3f-16147eab268b.PNG)

**Comment by shadab-skhan** [comment]
Fixed with #1192
