### ISSUE TITLE
[NGRM] - Cell centered properties is misaligned

### ISSUE THREAD

**Issue by shadab-skhan** [equinor/webviz-subsurface-components#1192]
Here is the comment from Christophe:

First, for cell-centered properties, we have one less sample in each direction than the grid.
For an [nx, ny] grid (these are the number of nodes), there are [nx-1, ny-1] cells, thus the cell-centered property is an array of [nx-1, ny-1].
Looking at webviz code, I found that webviz-subsurface-components/react/src/lib/components/DeckGLMap/layers/map/mapLayer.ts is probably wrong on line 266:
const propertyValue = propertiesData[i0];
i0 correctly refers to the grid node (in an [nx, ny] array), but incorrectly to the property value (which is in a [nx-1, ny-1] array).
The correct index will probably be propIndex = h * (nx - 1) + w;.

**Comment by nilscb** [comment]
There are two 2D input arrays. One for the depths and one for the properties.It is assumed that these two have the same dimension. When "cellCenteredProperties" are set to false
each node is colored according to the corresponding property value and the cell is linearly interpolated over the interior of the cell.

However if "cellCenteredProperties" is set to true that means the cell should be constant colored. The way this is implemented is that the property 2D array is displaced half a cell in each direction, effectively placing a property value in the middle of each cell and the cell will get the corresponding constant color. 

Also this means that the last column and the last row of the property 2D array are disregarded. This is just how it is implemented for now but that can of course be changed if there are better ways.

I use the python library "roxar2raster" (written by Håvard I belive). This library takes surfaces from a RMS project and produce 2D property or depth array in float32 or png format and according to the definition above.

I attached a figure illustrating this.

[depth_and_property_array_layouts.pptx](https://github.com/equinor/webviz-subsurface-components/files/9567780/depth_and_property_array_layouts.pptx)

**Comment by shadab-skhan** [comment]
Here are the current and expected display from Christophe:
Current display:
![image](https://user-images.githubusercontent.com/9147767/190314420-7e2fd2a3-e6fb-4360-af2f-fab13eddad29.png)

Expected display:
![image](https://user-images.githubusercontent.com/9147767/190314454-12b03f89-0a39-4097-9282-d663f3c33782.png)

**Comment by nilscb** [comment]
Also note: There are two map layers currently. 
map3DLayer.ts under the terrain folder. This uses delatin algorithm resulting in fewer triangless

mapLayer (under the map folder) This generates two triangles for every cell. This is the one you should use.
