### ISSUE TITLE
WellLogViewer/SyncLogViewer - Missing export and proptypes

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1228]
Some minor issues encountered when attempting to use some functionality in Dash:

- [x]  `SyncLogViewer` is not exported at top-level so it is not visible in Dash.
- [x] propTypes not defined for `wellpick` in WellLogViewer
- [x] propTypes not defined for `wellpicks`, `spacers` and `wellDistances` in SyncLogViewer.

**Comment by Vladimir-Kokin** [comment]
Missing export and proptypes fixed in  #1229
