### ISSUE TITLE
DeckGL component fails and stops responding to callbacks if given empty "views"

### ISSUE THREAD

**Issue by oysteinequinor** [equinor/webviz-subsurface-components#1231]
As part of a dynamically set up page, we are initially not presenting any views. We previously solved this by initializing the DeckGL component `views` property with an empty dict. Upgrading from `0.4.14a5` to `0.4.14rc2` this no longer works.

Setting `views` to empty dict now crashes in the browser with:
> TypeError: Cannot read properties of undefined (reading '0')
>      at Map (Map.tsx?b604:307:9)

The fix for us is to just not set the `views` property at initialization. But this means that any bug in our code that accidentally sets the `views` to an empty dict will break the DeckGL component for the user, until a page refresh.

I am not sure if this should be considered a bug.

Example to reproduce on `0.4.14rc2`:
```python
import dash
import webviz_subsurface_components

layers = [
    {
        "@@type": "GeoJsonLayer",
        "id": "layer1",
        "data": {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "geometry": {
                    "type": "GeometryCollection",
                    "geometries": [{"type": "Point", "coordinates": (0, 0)}],
                },
            }],
        },
        "getPointRadius": 1,
    }
]
views = {
    "layout": [1, 1],
    "viewports": [
        {
            "id": "layer1",
            "name": "asdf",
        },
    ],
}

app = dash.Dash(__name__)
app.layout = webviz_subsurface_components.DeckGLMap(
    id="map",
    layers=[],
    bounds=[-1.0, -1.0, 1.0, 1.0],
    views={},  # Commenting out this line fixes the issue
)

@app.callback(
    dash.Output("map", "layers"),
    dash.Output("map", "views"),
    dash.Input("map", "layers"),
)
def test(_):
    return layers, views

app.run_server()
```

**Comment by hkfb** [comment]
Sounds like a bug. We should handle an empty `views` prop gracefully.
