### ISSUE TITLE
Being able to set number of visible tracks in well correlation

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface-components#1240]
Currently we show three tracks by default per well (in addition to depth tracks). User has requested to show all tracks (and instead scroll horizontally to see the other wells).

**Comment by Vladimir-Kokin** [comment]
There is prop maxVisibleTrackNum (default 2 for horizontal and 3 for vertical orientation)

**Comment by shadab-skhan** [comment]
available with the maxVisibleTrackNum prop
