### ISSUE TITLE
Remove lateral scale when in 3D mode

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface-components#1321]
The map component currently shows lateral scale also in 3D mode. When camera is tilted (which is typically the case in 3D), the value of the lateral scale is limited and could potentially easily be misleading. Should we remove the scale when in 3D mode?

Spin off from #1318.

**Comment by hkfb** [comment]
I agree, I think it's confusing in 3D. However, as it is the client can explicitly control the visibility when toggling 2D/3D, so we could leave it up to the client to control the behavior.
