### ISSUE TITLE
SyncLogViewer: Possibility to set wellpickFlatting by callback

### ISSUE THREAD

**Issue by SteffenEq** [equinor/webviz-subsurface-components#1346]
Hi,

Would it be possible to allow callbacks to set wellpickFlatting, and to set this to only one horizon, e.g., making the resolution for each log the same?

Thanks

**Comment by hkfb** [comment]
@Vladimir-Kokin what do you think?

**Comment by Vladimir-Kokin** [comment]
prop wellpickFlatting is array of one or two elements with horizon names.
when only one element is used than resolution for each log is the same (when prop syncContentDomain is true)

**Comment by SteffenEq** [comment]
@Vladimir-Kokin 
You're right, having syncContentDomain true and setting only one wellpickFlatting works. My bad. Thank you!
