### ISSUE TITLE
Error when selecting color scale

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#1353]
When selecting a color scale in this example https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/deckglmap--color-map-layer-color-selector it gives an error in the console:

![Screenshot from 2022-12-08 11-32-29](https://user-images.githubusercontent.com/19621822/206424865-e3379cb7-86f6-4974-a946-5346fa3ef4d2.png)

**Comment by shruthirai** [comment]
Resolved in PR https://github.com/equinor/webviz-subsurface-components/pull/1368
