### ISSUE TITLE
Change of view in storybook the view does not get update in the storybook

### ISSUE THREAD

**Issue by VincentNevermore** [equinor/webviz-subsurface-components#1383]
If I set views to something valid in the story, then the view does not update. Maybe there is some missing update.

![image](https://user-images.githubusercontent.com/39239025/211319445-7a43c300-23b7-42da-a0d1-017cc0440b0d.png)

**Comment by hkfb** [comment]
@VincentNevermore which story is this?

**Comment by VincentNevermore** [comment]
> @VincentNevermore which story is this?

This is the MultiAnnotation User Story. But I think it does not really matter which story it is, I tried on the depth one and it also shows similar issue when I try to update the view
