### ISSUE TITLE
Cannot position colorlegend in Dash

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1389]
To reproduce:
- Replace `children` in the [python annotation example](https://github.com/equinor/webviz-subsurface-components/blob/master/examples/deckgl_annotation.py) with:

```python
    children=[
        wsc.ViewAnnotation(
            id="view_1",
            children=[
                wsc.ViewFooter(children="Hugin"),
                wsc.WebVizContinuousLegend(
                    "test",
                    min=0,
                    max=10,
                    colorName="seismic",
                    horizontal=True,
                    position=[16, 10], # <- Has no effect
                ),
            ],
        ),
        wsc.ViewAnnotation(id="view_2", children=[wsc.ViewFooter(children="sdfsfd")]),
    ]
```

The legend is locked to the top left. Using the `position` prop does not have any effect.

**Comment by shruthirai** [comment]
This is because currently we do not have position prop in the latest version of color component but instead it can be positioned using prop cssLegendStyles (implemented by Amro).

**Comment by shruthirai** [comment]
No, this prop is not yet used in Webviz.

**Comment by shruthirai** [comment]
> No, this prop is not yet used in Webviz.



> > This is because currently we do not have position prop in the latest version of color component but instead it can be positioned using prop cssLegendStyles (implemented by Amro).
> 
> Is the `cssLegendStyles` exposed from the WebVizContinuousLegend component?

No, this prop is not yet used in Webviz.
