### ISSUE TITLE
Logic to select either discrete or continuous color legend has to be done manually in Dash

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1390]
In the color-tables repo there is a [ColorLegend](https://github.com/emerson-eps/color-tables/blob/main/react-app/src/component/Legend/ColorLegend.tsx) component that renders either a continuous legend or a discrete legend based on the provided colortable.

This component is not exposed in Dash. Only `WebVizContinuousLegend` and `WebVizDiscreteLegend` are available.
It would be beneficial to have the wrapping `ColorLegend` exposed so that we don't need to handle this logic on the Dash side.

**Comment by shruthirai** [comment]
Just for the information : The main idea for using ColorLegend component is for using color selector component but if we want to use continuous or discrete legend independently without the color selector then we can directly import it for ex in Webviz we have (import { ContinuousLegend } from "@emerson-eps/color-tables";)

**Comment by hkfb** [comment]
> Just for the information : The main idea for using ColorLegend component is for using color selector component but if we want to use continuous or discrete legend independently without the color selector then we can directly import it for ex in Webviz we have (import { ContinuousLegend } from "@emerson-eps/color-tables";)

This won't work right now because they are not generated as Dash components. For the short term we could fix this with a new wrapper component (like `WebVizContinuousLegend`).
