### ISSUE TITLE
Pie layer is not possible to toggle on/off from the toolbar selector

### ISSUE THREAD

**Issue by tagr71** [equinor/webviz-subsurface-components#1400]
The pies are not possible to toggle on/off from the toolbar selector. I have tested this on the following pre-releases: 

0.4.14-alpha.5
0.4.15-alpha.2
0.4.14-alpha.3
0.4.14-alpha.4
0.4.14-alpha.5
0.4.14-alpha.6
0.4.14-alpha.7
0.4.15-rc.0
0.4.15-rc.1

and the pie layer has not been possible to turned on/off in any of these pre-releases.

**Comment by hkfb** [comment]
This is intentional. We decided that it should be up to the consumer of the component to change the visibility of layers. The `toolbar` prop is obsolete and should not be used.
