### ISSUE TITLE
Issues with map colorlegends in Dash

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1410]
In addition to #1390 there are other issues with color legends in Dash:
- Currently not possible to display tick marks. (Relevant props not available in `WebVizContinuousLegend` and `WebvizDiscreteLegend` ?).
- Color legends for multiple views does not work correctly. E.g. it is not possible to have different `colorName`. They all seem to be controlled from the first view.

**Comment by shruthirai** [comment]
@HansKallekleiv About the first point, yes, currently there is no prop for tickmark exported to dash, which I will do changes and submit. About the second point, need to check or maybe @hkfb knows better ?

**Comment by HansKallekleiv** [comment]
That is good to know 👍 
It sounds like exposing the `ColorLegend` component to Dash should fix most issues.
There are no reasons to use `ContinuousLegend`and `DiscreteLegend` in Dash then.

**Comment by shruthirai** [comment]
@HansKallekleiv @hkfb About the second point (it is not possible to have different colorName), I just figured out that if you pass different colorName and id prop to the continuous legend , it works. May be you are missing id prop @HansKallekleiv ? .
