### ISSUE TITLE
[NGRM] -  Z values should be defined geological part 2. Rename "isZDepth" to "ZIncreasingDownwards"

### ISSUE THREAD

**Issue by nilscb** [equinor/webviz-subsurface-components#1417]
This is a wish from the viewers team. It is the name for the same property in  resqml,

**Comment by t0oF-azpn** [comment]
Just to clarify: there is no need to match ResqML name.
But there is definitively the need to have a batter name. The current name `isZDepth` is not explicit, especially if there is a `depthTest` flag.

`ZIncreasingDownwards` was only a proposal because it is really explicit ;)
