### ISSUE TITLE
Add SVG track to WellLogViewer

### ISSUE THREAD

**Issue by SteffenEq** [equinor/webviz-subsurface-components#1445]
Users ask for strat. column tracks in WellLogViewer.

Suggest to add such example (SVG track) to stories. See e.g. https://github.com/equinor/videx-wellog

Thanks!

**Comment by hkfb** [comment]
CC @Midtveit

**Comment by Midtveit** [comment]
Clarification the example above means the frm (formation track) is that correct.
So this is a discrete log with color and label, Label shown with vertical line from top depth to bottom depth.
a horizontal line is indicating changes.
