### ISSUE TITLE
[NGRM] - Copied views in matrix view cannot be manipulated directly

### ISSUE THREAD

**Issue by mmatselinskiy** [equinor/webviz-subsurface-components#1478]
Actual: after adding a view, it cannot be manipulated directly:

![Video_2023-04-24_152044_AddViewManipulation800x600](https://user-images.githubusercontent.com/110110850/234007441-f82eaf32-e544-45c9-b15e-bd3671a48aa9.gif)

Expected: after adding a view, it should be responsive as any other view

Workflow:
- open a component with matrix view
- manually add another view to the matrix
- try to manipulate it -> fail
- turn on the view synchronization for the new view and manipulate the other (sync'd) view -> works ok

**Comment by nilscb** [comment]
When pasting in the view its id field is not changed. It is important that all the views have unique id's.
Closing this issue,
