### ISSUE TITLE
Axes 2D gets scrambled when to much zoom is applied.

### ISSUE THREAD

**Issue by nilscb** [equinor/webviz-subsurface-components#1524]
Go to this story: https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer-axes2d--base

Apply lots of zooming in and observe that the axes gets scrambled.

**Comment by anders-kiaer** [comment]
Is this closed by #1523 @nilscb?

**Comment by nilscb** [comment]
I will close this one
