### ISSUE TITLE
webviz_subsurface_components.WellLogViewer - max curves allowed

### ISSUE THREAD

**Issue by daniel-dura** [equinor/webviz-subsurface-components#1553]
Hi,

At the moment, I have noticed that the maximum number of curves allowed to be plotted is 12. 

Is there any way to increase the number of curves plotted?

**Comment by hkfb** [comment]
CC @Vladimir-Kokin

**Comment by hkfb** [comment]
@daniel-dura is that # curves per track? Do you have an example?

**Comment by daniel-dura** [comment]
Yes, let's say 12 different curve names (plots) side by side ->                                                                                                                                       track = {
            "title": curve_name,
            "plots": [{"name": curve_name, "style": "continuous"}]
        }

**Comment by Vladimir-Kokin** [comment]
@daniel-dura "side by side" is not for many plots on one track. It is for many tracks with on plot each.
Anyway I can add 15 plot to one track
![изображение](https://github.com/equinor/webviz-subsurface-components/assets/86053741/4db5a6bf-aec6-4dec-88f3-843a75d4d970)
Or set 15 simultaneously visible tracks (maxVisibleTrackNum option)
```
Default.args = {
    id: "Well-Log-Viewer",
    horizontal: false,
    welllog: require("../../../../example-data/L898MUD.json")[0],   // eslint-disable-line
    template: require("../../../../example-data/welllog_template_1.json"),// eslint-disable-line
    colorTables: colorTables,
    wellpick: wellpick,
    axisTitles: axisTitles,
    axisMnemos: axisMnemos,
    viewTitle: true, // show default welllog view title (a wellname from the welllog)
    options: {
        hideTrackTitle: false,
        hideTrackLegend: false,
        maxVisibleTrackNum: 15,
    },
};
```
![изображение](https://github.com/equinor/webviz-subsurface-components/assets/86053741/3daf363d-6826-4a38-90a7-738b4c851748)

**Comment by Vladimir-Kokin** [comment]
@daniel-dura 
in the **options** prop you could set **maxVisibleTrackNum** for desired value
