### ISSUE TITLE
[NGRM] - @webviz/well-log-viewer should not be dependent on @webviz/subsurface-viewer

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1586]
@webviz/well-log-viewer lists @webviz/subsurface-viewer as a dependency. 
As discussed in the webviz alignment meeting, currently the dependency occurs because of a use-case example in storybook. This example should be removed or moved to the story level and the packages should not be dependent on each other.

**Comment by hkfb** [comment]
Fixed in #1628.
