### ISSUE TITLE
[NGRM] - discrete logs are not displayed correctly in horizontal mode in Well Log Viewer

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1587]
Discrete facies logs are not displayed correctly on horizontal mode - it seems that they are still being rendered vertically in the horizontal track and also zoom works incorrectly on them.

Vertical:
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/4f187716-6b1d-4c2f-9606-c18a5fd7b26b)
Horizontal: 
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/9ef04118-8b58-4197-aba8-1462b51790c5)

**Comment by hkfb** [comment]
CC @Vladimir-Kokin

**Comment by Vladimir-Kokin** [comment]
class StackedTrack from [videx-wellog](https://github.com/equinor/videx-wellog) has no support of horizontal track orientation

**Comment by mirisb** [comment]
Fixed in Videx code
