### ISSUE TITLE
Performance improvements to `makeFullMesh` function in `MapLayer`

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz-subsurface-components#1662]
Low hanging improvements:
- [ ] Use `Float32Array` instead of regular JS arrays and allocate up front
- [ ] Do not calculate what is not required (split up in several functions/`WebWorkers`?)
- [ ] Send data to `WebWorker` as transferable objects
       https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
       https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects)
- [ ] Allow input to `MapLayer` as `Float32Array`

Additional potential improvements:
- [ ] Reuse triangle vertices for lines
- [ ] Constant z in flat maps
- [ ] `WebWorker` still required?
- [ ] Normals as signed byte

**Comment by HansKallekleiv** [comment]
Related #1665
