### ISSUE TITLE
`SubsurfaceViewer` with `MapLayer`  initializes two `makeFullMesh` webworkers

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#1665]
See storybook. For example: https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer-map-layer--small-map

![image](https://github.com/equinor/webviz-subsurface-components/assets/16436291/fb69b341-085e-45e8-850f-61cdaa2f7878)

**Comment by nilscb** [comment]
Webworker is removed from MapLayer now.
