### ISSUE TITLE
Regression - view object initialized as empty

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#1678]
The [view-object-initialized-as-empty story](https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer--view-object-initialized-as-empty) appears to be broken.

@nilscb

**Comment by nilscb** [comment]
This works now, Probably fixed by PR "ci: Add script to workflow for testing storybooks. (#1750)" merged Nov 3.

**Comment by nilscb** [comment]
This works now, Probably fixed by PR "ci: Add script to workflow for testing storybooks. (https://github.com/equinor/webviz-subsurface-components/pull/1750)" merged Nov 3.
