### ISSUE TITLE
ColormapLayer and Hillshading2DLayer are "rugged"

### ISSUE THREAD

**Issue by SteffenEq** [equinor/webviz-subsurface-components#1692]
In some situations ColormapLayer and HillShading2DLayer are rugged, see snapshots from static storybook below. Turning off Hardware acceleration in the browser seem to fix this, but then the deck.gl component becomes very slow. Is this perhaps some problem with the resolution?

Thanks!

![image](https://github.com/equinor/webviz-subsurface-components/assets/107108124/6e4bd68b-be24-49fa-af2e-db43c1adac91)
![image](https://github.com/equinor/webviz-subsurface-components/assets/107108124/ba3d879a-642d-442c-b2a2-11b96a05a2cb)

**Comment by hkfb** [comment]
Have you considered using the `MapLayer` instead?

**Comment by SteffenEq** [comment]
We'll try that out, thanks! Also, after upgrading GPU drivers, the rugged effect disappeared. Could perhaps close this issue as it seems to be a webgl/GPU problem.
