### ISSUE TITLE
Null values interpreted as 0 in MapLayer - DashSubsurfaceViewer in python

### ISSUE THREAD

**Issue by eirik-morken** [equinor/webviz-subsurface-components#1709]
Related to this issue that I think should have been solved?
https://github.com/equinor/webviz-subsurface-components/issues/1642

I should have the newest version of the pypi package (1.0.0) installed but I still experience the "wall" issue with null values where it is set to 0 instead of null.  I use python.

![image](https://github.com/equinor/webviz-subsurface-components/assets/72235758/afb5b79b-a965-4c5c-8eb8-708a7c43f611)

**Comment by hkfb** [comment]
Can you show some example code?

CC @nilscb

**Comment by eirik-morken** [comment]
view = [DashSubsurfaceViewer(
                    coords={"visible": True},
                    scale={
                    "visible": True  # Set to False to hide the scale
                },
                    id='surface_grid',
                    coordinateUnit = "m",
                    views = {
                        "layout": [1, 1],
                        "showLabel": False,
                        "viewports": [
                            {
                                "id": "deck_view",
                                "show3D": dimension,
                                "layerIds": layersid,
                                "isSync": True
                                },
                                ],
                                },
                                bounds = [
                    depth_surface.xmin,
                    depth_surface.ymin - (depth_surface.ymax-depth_surface.ymin)*0.1,
                   
                    depth_surface.xmax,
                    depth_surface.ymax + (depth_surface.ymax-depth_surface.ymin)*0.1,
                  
                ],
                layers=[
                    {
                        "@@type": "AxesLayer",
                        "id": 'AXES_LAYER',
                        "bounds": [
                                depth_surface.xmin,
                                depth_surface.ymin,
                                np.nanmin(depth_surface.values) * multiplication_factor,
                                depth_surface.xmax,
                                depth_surface.ymax,
                                np.nanmax(depth_surface.values) * multiplication_factor,
                                ]},
                            {
                                "@@type": "MapLayer",
                                "id":'MAP_LAYER',
                                "meshData": depth_surface.get_values1d(order="F", asmasked=True).astype(np.float32) * multiplication_factor,
                                "ZIncreasingDownwards" : True,
                                
                                "frame": {
                                    "origin": [depth_surface.xori, depth_surface.yori],
                                    "count": [depth_surface.ncol, depth_surface.nrow],
                                    "increment": [depth_surface.xinc, depth_surface.yinc],
                                    "rotDeg": depth_surface.rotation,
                                    },
                                    "contours": [0, 50],
                                    "isContoursDepth": True,
                                    "gridLines": False,
                                    "material": True,
                                    "colorMapName": colormapname,
                                    "name": "mesh",
                                    },
                         
                                    ]),
                                    GraphDataModel.check_reduced_blob(reduced_factor) 
                                    ]

**Comment by eirik-morken** [comment]
Where depth_surface is a XTGeo regulargrid

**Comment by eirik-morken** [comment]
webviz_subsurface_components-1.0.1a0

**Comment by nilscb** [comment]
I will have a look at this today.

**Comment by eirik-morken** [comment]
multiplication_factor is either 1 or -1 btw 😄

**Comment by hkfb** [comment]
> webviz_subsurface_components-1.0.1a0

I don't have an overview of the python packages. Maybe @HansKallekleiv or @rubenthoms knows if this package is up to date?

**Comment by rubenthoms** [comment]
`webviz_subsurface_components-1.0.1a0` was released before your changes were merged into main, @nilscb. Hence, releasing a new version might fix your issue, @eirik-morken. I can create a new one today.

**Comment by nilscb** [comment]
I think perhaps both things need to happpen. Do not send null values to webviz use NaN if possible

**Comment by eirik-morken** [comment]
I already am using numpy NaN as far as I remember, so will doublecheck and wait for new release 🙂

**Comment by HansKallekleiv** [comment]
the problem is that Dash serialize meshData to json. Any `NaN` values will be converted to `null` by the serializer.
We have a few options here as far as I can see:
- Handle `null` values as `undefined` on the javascript side
- Encode the meshData before serializing. E.g. base64 encode on the Dash side. This will also require adding decoding on the javascript side.
- Serve the `meshData` as bytes on a separate flask route in the Dash application. 
Example here: https://github.com/equinor/webviz-subsurface-components/blob/master/python/examples/example_deckgl_map.py#L103 .
This will "bypass" the json serialization and keep the NaN values. This adds complexity on the Dash side, but it should work.

**Comment by eirik-morken** [comment]
Any updates on this, @hkfb @HansKallekleiv? Quite important for user experience as a lot of grids has null-values 🙂
Or even some workarounds on my side if it possible?

**Comment by hkfb** [comment]
> Any updates on this, @hkfb @HansKallekleiv? Quite important for user experience as a lot of grids has null-values 🙂 Or even some workarounds on my side if it possible?

Did you get a new release from @rubenthoms ?

**Comment by eirik-morken** [comment]
Not that I am aware of

**Comment by rubenthoms** [comment]
@eirik-morken @hkfb: There is a new release from October 19: https://pypi.org/project/webviz-subsurface-components/1.0.1a1/

**Comment by eirik-morken** [comment]
The one from october 19 does not fix the issue as far as I can tell 🙂

**Comment by rubenthoms** [comment]
@hkfb @nilscb where there any PRs fixing the issue since October 19?

**Comment by nilscb** [comment]
This layer receives the data either as an URL, a javascript native array or as a javascript Float32Array.
Im not sure which of these three will apply when you use Dash (I have not been able to run Dash myself for debugging on windows). In either case the data will be converted to Float32Arrays and in that process null values will automatically be converted to 0 by the Float32Array constructor. In the case that data are received as an URL or javascript native array it may be possible for webviz to filter out null values. But I guess the best solution is not sending null's in the first place.

**Comment by hkfb** [comment]
> the problem is that Dash serialize meshData to json. Any `NaN` values will be converted to `null` by the serializer. We have a few options here as far as I can see:

Is there a way prevent Dash from converting `NaN` to `null`? @eirik-morken @HansKallekleiv

**Comment by hkfb** [comment]
> * Encode the meshData before serializing. E.g. base64 encode on the Dash side. This will also require adding decoding on the javascript side.

This should also work as long as `depth_surface.get_values1d` outputs `undefined` as `NaN` @eirik-morken

**Comment by HansKallekleiv** [comment]
> Is there a way prevent Dash from converting `NaN` to `null`? @eirik-morken @HansKallekleiv

No I don't think so, but we can bypass it.

Dash is basically a Flask app that uses one endpoint to send/receive data. All data on this endpoint is serialized/deserialized in json. All Dash callbacks uses this endpoint and any data updates through callbacks will be serialized to json.

One solution is to register an additonal endpoint in the underlying Flask application.
This endpoint can listen to changes in the map URL and return data in other formats.

Here is a working example:
```python
import io
import requests
import numpy as np
import xtgeo
import dash
import webviz_subsurface_components as wsc

# Get a surface from example data
file_url = "https://github.com/equinor/webviz-subsurface-components/raw/master/python/examples/example-data/topvolantis_depth.gri"
response = requests.get(file_url)
xtg_surface = xtgeo.surface_from_file(io.BytesIO(response.content))

frame = {
    "origin": [xtg_surface.xori, xtg_surface.yori],
    "count": [xtg_surface.ncol, xtg_surface.nrow],
    "increment": [xtg_surface.xinc, xtg_surface.yinc],
    "rotDeg": xtg_surface.rotation,
}
app = dash.Dash(__name__)

app.layout = dash.html.Div(
    [
        wsc.DashSubsurfaceViewer(
            id="deckgl-map",
            layers=[
                {
                    "@@type": "MapLayer",
                    "id": "mesh-layer-as-bytes",
                    "meshUrl": "/map/some_identifier",  # Update this url from a callback
                    "frame": frame,
                },
            ],
        ),
        dash.dcc.Dropdown(
            id="map_identifier",
            options=[
                {"label": "some_identifier", "value": "some_identifier"},
                {"label": "some_other_identifier", "value": "some_other_identifier"},
            ],
            value="some_identifier",
        ),
    ]
)


@app.callback(
    dash.dependencies.Output("deckgl-map", "layers"),
    dash.dependencies.Input("map_identifier", "value"),
    dash.dependencies.State("deckgl-map", "layers"),
)
def update_surface(map_identifier, existing_layers):
    # Callback to update the map identifier in the map url
    existing_layers[0]["meshUrl"] = f"/map/{map_identifier}"
    return existing_layers


# Endpoint that listens to the map url and returns a map as bytes
@app.server.route("/map/<map_identifier>")
def send_map_as_bytes(map_identifier: str):
    # Add logic based on map_identifier to return different maps
    if map_identifier == "some_identifier":
        values = xtg_surface.values.astype(np.float32)
        values.fill_value = np.NaN
        values = np.ma.filled(values)
        values = np.rot90(values)
        byte_io = io.BytesIO()
        byte_io.write(values.tobytes())
        byte_io.seek(0)
        return byte_io
    if map_identifier == "some_other_identifier":
        values = xtg_surface.values.astype(np.float32) * np.random.rand()
        values.fill_value = np.NaN
        values = np.ma.filled(values)
        values = np.rot90(values)
        byte_io = io.BytesIO()
        byte_io.write(values.tobytes())
        byte_io.seek(0)
        return byte_io


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by eirik-morken** [comment]
I'll give it a try 👍

**Comment by eirik-morken** [comment]
With the combined genius of Hans, myself and chatGPT I managed to refactor it into my code using my cache, and it works 😁
Thank you for the help!

**Comment by nilscb** [comment]
chatGPT also!? Nice work :-)

**Comment by eirik-morken** [comment]
Proof that Hans + chatGPT is enough to give me the necessary guiding to solve this 😄 :
![image](https://github.com/equinor/webviz-subsurface-components/assets/72235758/db098409-f254-4a31-8b6f-18361c9d3c69)
