### ISSUE TITLE
[NGRM] - In WellLogViewer, title text is not displayed correctly when component size is reduced

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1715]
When reducing the size of the component, the titles of the tracks go up and get cropped from the top and barely visible:
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/294405d3-b8f9-4f5f-8fce-44b71c5c5820)
If reducing the size some more, the font size of the titles is adjusted such that the titles are visible:
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/26940d8e-b9f6-47d2-b2e5-29f595f8404b)

The font adjustments should be associated with the title width

**Comment by mirisb** [comment]
This bug is within Webviz implementation of stackLegendConfig which is responsible for legend display of a stacked track.

**Comment by Vladimir-Kokin** [comment]
The bug is not only in **stack** tracks but in **scale** track also.
![изображение](https://github.com/equinor/webviz-subsurface-components/assets/86053741/22fbd0bc-bc10-4c8c-a161-b2d7e0b3e35c)

**Comment by mirisb** [comment]
Size of title is still not computed correctly - the string is now cut on the width axis. see storybook example: 
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/c5e6756f-425f-48e7-beed-0c4db0e36a32)

**Comment by Vladimir-Kokin** [comment]
Too long titles for this width.
What can be done?

**Comment by mirisb** [comment]
If the user makes the track narrow we need to truncate the name (dynamically)

suggestions: 
1. truncate name and add ellipsis (...)
2. add tooltip to show full name when hovering on track title
