### ISSUE TITLE
[NGRM] - Well Log Viewer flickers when sliding to max zoom or hovering over different logs

### ISSUE THREAD

**Issue by sarahd52** [equinor/webviz-subsurface-components#1758]
- When using the mouse to slide to max zoom, there is a flickering effect while the mouse button is held down.
- Also when hovering over different facies (where the name does not all fit on one line)
- Right border of the Readoutbox is cut off

https://github.com/equinor/webviz-subsurface-components/assets/91009543/3092f200-9ba1-4a1d-9375-42160147b873

**Comment by hkfb** [comment]
CC @Vladimir-Kokin

**Comment by Vladimir-Kokin** [comment]
Fixed in #1877 (item 1. and 2.)
