### ISSUE TITLE
[NGRM] - SyncLogViewer component crashes when increasing number of wells

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1780]
When creating the SyncLogViewer component, callbacks class member is populated with callbacks for each WellLogView. However when adding another set of logs of well (WellLog) upon updating the component in componentDidUpdate, this member is not updated. 

When first rendering the SyncLogViewer with one WellLog, and then re-rendering it with two WellLogs, the component crashes. 
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/bf490698-619a-4c9f-9c93-b5e5659848ed)

**Comment by Vladimir-Kokin** [comment]
@mirisb componentDidUpdate is too late. It is called after render 
I add componentWillUpdate. It is called before render/
