### ISSUE TITLE
ZIncreasingDownwards = False makes the map float outside axis

### ISSUE THREAD

**Issue by eirik-morken** [equinor/webviz-subsurface-components#1832]
As far as I understand the ZIncreasingDownwards = False where the grid is "taller" with higher values, and should do the opposite as ZIncreasingDownwards = True where grid is "lower" with higher values. However it seems like it  resets something and thereby hovers outside the axis. It does not reverse the heights.

Recreated in viewer:
https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer-map-layer--map-layer-3-d-png&args=layers[1].ZIncreasingDownwards:!false

![image](https://github.com/equinor/webviz-subsurface-components/assets/72235758/d6c14d9a-6a52-43b1-9afa-e3b5199b89d8)

**Comment by nilscb** [comment]
So, if you set ZIncreasingDownwards = True then positive  map values will be interpreted as depths and the map will appear "down" below 0. If you set it to False the map will appear above zero as shown in your figure. There is a ZIncreasingDownwards property on the 3D axis layer also and you will probably set that one also to ZIncreasingDownwards  = False then the axis box will enclose the map (and not shown separated as in your figure)

**Comment by eirik-morken** [comment]
That solved my issue, thanks 😁
