### ISSUE TITLE
After setting multiPicking to True, get lag when scrolling/moving while mouse pointer on grid

### ISSUE THREAD

**Issue by eirik-morken** [equinor/webviz-subsurface-components#1838]
Happened after fixing this: https://github.com/equinor/webviz-subsurface-components/issues/1828

The multiPicking parameter = True makes the depth property show correctly. However it introduces some major performace issues.
It seems like when you try to zoom with scroll bar while moving the mouse over the grid there is a large noticeable lag. 
When not moving over grid but moving over empty space and scrolling then no lag is registered. 
This also happens when trying to rotate grid while mouse pointer is over the grid, but not to that great extent. Still noticeable and reducing the quality of the user experience.

Do not know if bug/unoptimized code or maybe the movement needs to be processed before the multiPicking parameters.

The scrolling issue can consistently be recreated in the storybook,.
Moving of the grid is harder to provoke in storybook but still happens sometimes.

**Comment by nilscb** [comment]
Try setting pickDepth to something different than its default (10) For instance 1 or 2.
The picking is expensive performance vice but I have not noticed it much in any storybook.


```
/**
 * Parameters for the InfoCard component
 */
coords?: {
    visible?: boolean | null;
    multiPicking?: boolean | null;
    pickDepth?: number | null;
};
```

**Comment by eirik-morken** [comment]
Setting pickDepth to 1 seems to have solved the issue. Thank you 🙂
