### ISSUE TITLE
 WellLogViewer multiple curves in same box, how to normalize endpoints

### ISSUE THREAD

**Issue by eirik-morken** [equinor/webviz-subsurface-components#1853]
I have this WellLogViewer

![image](https://github.com/equinor/webviz-subsurface-components/assets/72235758/025d728a-b9c4-48ef-a425-57b61df02367)

What parameters must I set to normalize the curves, so both get 55 to 155 instead of one having 60 to 135 ? Did not figure it out from the storybook documentation. 😁

**Comment by mirisb** [comment]
Values domain is given by the domain field in TemplatePlotProps which is part of the plot template. You need to provide the range of the domain to control the log values range.

**Comment by eirik-morken** [comment]
Forgot to specify that it is in python. Is there a code example of where to change change them and which parameters to change?
The links here are broken/404. 

https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/docs/welllogviewer-overview--docs

**Comment by eirik-morken** [comment]
@hkfb Do you know of any examples? Or someone who knows? Hard to guess when I can't see any parameters below the top level in the python documentation of WellLogViewer😁

**Comment by hkfb** [comment]
> @hkfb Do you know of any examples? Or someone who knows? Hard to guess when I can't see any parameters below the top level in the python documentation of WellLogViewer😁

@eirik-morken I'm afraid you are blazing the trail if using the WellLogViewer with Python. Can you post an example? Maybe @HansKallekleiv can help?

**Comment by eirik-morken** [comment]
Do you have an example in another language then? Should be comparable in format I guess.

**Comment by hkfb** [comment]
> Do you have an example in another language then? Should be comparable in format I guess.

You can play around with [this example](https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/welllogviewer-components-welllogview--default&args=template.domain[0]:10;template.domain[1]:100).

I added the `domain` field that @mirisb mentioned, but I'm not sure exactly what it does.

@Vladimir-Kokin any ideas?
