### ISSUE TITLE
[NGRM] - Provide callback API to receive legend readout information for syncLogViewer

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1875]
Currently legend readout is displayed only by the legend component. We want to allow the client application to chose how to display the legend on their own and not through the legend component. They request to get the readout from the component as a record so that they can show it.

There is the option of using a controller however controller is per view (single well) in SLV and not for the whole component.

**Comment by Vladimir-Kokin** [comment]
The information for displaying readout could be obtained on already existing callbacks
```
 onContentRescale?: (iView: number) => void;
 onContentSelection?: (iView: number) => void;
 onTemplateChanged?: (iView: number) => void;
```
with WellLogController interface (getX... functions) for correspontent view

@mirisb Is it not enough to make own readout?

**Comment by mirisb** [comment]
Controller is per view and thus corresponds to the well the mouse is hovering. It is possible to add work that reads the selection from all wells and logs, however I need to check performance if doing it from our end. Let me try and see if it fully meets requirements and if any performance issues arise.

**Comment by mirisb** [comment]
Fixed in Viz by using controllers as suggested by @Vladimir-Kokin
