### ISSUE TITLE
DashSubsurfaceViewer, MapLayer, Python - Retain camera postion when changing map parameters

### ISSUE THREAD

**Issue by eirik-morken** [equinor/webviz-subsurface-components#1885]
Is there a way to make the map keep its camera position when changing map parameters like color etc, instead of resetting to default?
Or maybe even a way to extract the current camera position and input it when updating other parameters?
I believe there was an earlier version that supported this. Has it been removed again?

**Comment by t0oF-azpn** [comment]
I should not be reset (at least in typescript, I don't know with python).
Can you elaborate your use-case ?
If you can demonstrate it on https://equinor.github.io/webviz-subsurface-components/storybook-static, it would be perfect !

**Comment by eirik-morken** [comment]
Then I will have to do some more experimentation 👍

**Comment by eirik-morken** [comment]
I finally figured out how to do this using the Patch functionality in dash 😊
Its quite genius when you understand how it connects to the different items.

with Output('divdeck', 'children') where the DashSubsurfaceViewer is a child in divdeck children [ ]
grid_settings["color"] could be e.g. "Rainbow"

```
patched_grid = Patch()
patched_grid[0]["props"]["layers"][0]["colorMapName"] = grid_settings["color"]
return patched_grid

```
