### ISSUE TITLE
[NGRM] WLV callback to reset component to given props

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1993]
In WellLogViewer\SyncLogViewer we would like to have a callback to reset the component to the props it was given to restore initial display. This is request applies to zoom level and scrolling position which can be changed by the user without affecting the provided props.

**Comment by Vladimir-Kokin** [comment]
This may be closely related with #2022

**Comment by mirisb** [comment]
fixed by #2047
