### ISSUE TITLE
[NGRM] - Scrolling is erratic when flattening in sync log viewer

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#2035]
Scrolling in sync log view behaves erratically (where it should be smoothed) if the wells are flattened according to well pick. This can also be observed in internal Webviz storybook: 
https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/welllogviewer-demo-synclogviewer--default&args=syncTrackPos:!false;syncContentSelection:!false

**Comment by Vladimir-Kokin** [comment]
As I undertnasd scrolling with a scroller not with mouse drag.
