### ISSUE TITLE
Incorrect depth readout in Grid3D layer after vertical re-scaling 

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#2086]
The grid3d layer has the same behaviour as in #2017 
https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer-grid3d-layer--simgrid

**Comment by w1nklr** [comment]
Thanks for the report.

@nilscb can you verify that the fix is applied also on the other layers ?
