### ISSUE TITLE
[NGRM] - SyncLogViewer is not working if wrapped with React.StrictMode component

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#2110]
Introduction: 
React.StrictMode component is used to debug components and make sure they are written correctly.  https://react.dev/reference/react/StrictMode
StrictMode is only active in dev mode thus it is not in effect when running production mode. 

Problem:
When wrapping SyncLogViewer in StrictMode it becomes disfunctional:
![dfc100ca-19f3-49d7-baff-8f46287ca0d4](https://github.com/equinor/webviz-subsurface-components/assets/18436935/691bde71-db16-42b1-9252-e9f600c2ac67)

Also in Dev Tools console we see errors:
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/e052ef8b-b3e5-494e-a768-0ffc22f77373)

This problem is interfering with development and also indicates a malfunction in the SyncLogView component.

**Comment by Vladimir-Kokin** [comment]
One sort of strict mode warnings in the console was removed in PR #2087 ([commit](https://github.com/equinor/webviz-subsurface-components/pull/2087/commits/449090af1e51dbf0fc4876de23e2779e09e8c326))
Another sort of warning (as in the issue description) still exists

**Comment by mirisb** [comment]
After #2139 there are no more errors in console while strict mode is active and component is working smoothly.
