### ISSUE TITLE
[NGRM] - error in console after removing a track

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#2114]
In story https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/welllogviewer-demo-synclogviewer--discrete-logs, when toggling off a well there is an error in the console: 
![image](https://github.com/equinor/webviz-subsurface-components/assets/18436935/bcfc6bc9-83bd-4f34-88a6-9d00438d96b4)

**Comment by Vladimir-Kokin** [comment]
One sort of strict mode warnings was removed in PR #2087 ([commit](https://github.com/equinor/webviz-subsurface-components/pull/2087/commits/449090af1e51dbf0fc4876de23e2779e09e8c326))
Another sort of warning (as in the issue description) still exists
