### ISSUE TITLE
Functionality to interact with a layer object

### ISSUE THREAD

**Issue by ashildskalnes** [equinor/webviz-subsurface-components#225]
It would be very useful if a layer object - e.g. a well path - become activated when hovered over so that when clicking on the object some action could be triggered, like opening a pop-up window with more information, images, etc.

**Comment by HansKallekleiv** [comment]
Implemented in `LeafletMap`
https://github.com/equinor/webviz-subsurface-components/tree/master/src/lib/components/LeafletMap#-listeners
