### ISSUE TITLE
Hillshading and shadows "follows the colormap"

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface-components#242]
Hillshading/shadows currently "follow the colormap", in the sense that instead of adding black/grey (vith varying degree of transparency), it instead tunes colors with the existing colormap.

Makes more sense to add amount of black wrt. shadows, instead of going down on data colormap?

**Comment by thor85** [comment]
I would vote for black shadows as default at least. Should not be dependent on colormap. Add a seperate parameter for shadow color if necessary (probably not?).
