### ISSUE TITLE
Well layers and pie charts (Emerson)

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#315]

**Comment by HansKallekleiv** [comment]
Well logs or completions color the trajectory (line), Drawing order supported, Discrete and scalar logs, color table support transparency
Depth thickmark (major, minor) with label on trajectory line or at angle
Well name and symbol placed at top, bottom, @MD
Pie charts for Production rates and other
Well name, MD, TVD, X, Y readout

**Comment by hkfb** [comment]
@HansKallekleiv What is meant by "Drawing order" in this context?

**Comment by anders-kiaer** [comment]
Is this issue approx. resolved? Should we remove any (if any) remaining items to separate issues with reduced scope (compared to this "epic")? 🙂
