### ISSUE TITLE
Show coordinates on LayeredMap

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#33]
A user needs to see the coordinates the LayeredMap is set to.
Investigate what option is the best:
- Coordinate axis  ([example](http://www.physicalgeography.net/fundamentals/2b.html))
- Coordinate on mouseover
- Other...

**Comment by anders-kiaer** [comment]
+1 for
> coordinate on mouseover
as that perhaps gives less visual clutter. But it could e.g. be shown as «two moving ticks» along the two different coordinate axes. Then it is visually ease to add units as well, e.g. UTMX (km), UTMY (km), TWT (s), «distance along intersection (km)» etc

**Comment by HansKallekleiv** [comment]
Perhaps both?
Some small ticks along the axes with an on/off toggle and a mouseover for more specific values.

I do think we need axis, or some other static display of coordinates, for the unavoidable use case of taking screenshots...
