### ISSUE TITLE
Hosted demo does not load the DeckGL layers

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#355]
https://equinor.github.io/webviz-subsurface-components/
The image based layers does not display.

@alexandruandrei91

**Comment by alexandruandrei91** [comment]
I can see the map properly on both firefox and chrome. Anyone else can reproduce the problem?
@anders-kiaer @nilscb @aprilzhang @hkfb 
![Screenshot 2021-04-29 102401](https://user-images.githubusercontent.com/57130720/116522160-25c37900-a8d5-11eb-9b22-bc5f44ee7d6f.jpg)

**Comment by HansKallekleiv** [comment]
It seems imgur is blocked on the company intranet.
We should perhaps put those images on github.
