### ISSUE TITLE
Stratigraphic levels and tree-filtering functionality in WellCompletion component

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-subsurface-components#365]
Problem:
When there are many stratigraphical zones in the data input, filtering out the zones you want to see can be cumbersome.

Solution:
Introducting a tree structure in the stratigraphical input where the zones can be grouped and filtered on different levels. Something like this: https://github.com/dowjones/react-dropdown-tree-select#screenshot

Also it could be useful to be display the data on different stratigraphical levels.

**Comment by anders-kiaer** [comment]
As pointed out by @aprilzhang - related to #282.
