### ISSUE TITLE
`WellCompletion` drawer filter

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface-components#383]
I'm not sure if it is a minor bug or not with `WellCompletion` component, but with the below layout it appears to be difficult to use the filter drawer without getting UI issues.

I think perhaps that expected behavior would be that width of `WellCompletion` root div is kept constant when opening the filter drawer (before it is opened the `WellCompletion` instance is correctly filling up the `100%` available width).

```python
import json

import dash
import dash_html_components as html

import webviz_subsurface_components

with open("../src/demo/example-data/well-completions.json", "r") as json_file:
    data = json.load(json_file)

app = dash.Dash(__name__)


app.layout = html.Div(
    style={"display": "flex", "flexDirection": "row", "width": "100vw"},
    children=[
        html.Div(
            # including "flexShrink": 0 --> filter drawer opens up to the right off-screen
            # not include "flexShrink": 0 --> left menu shrinks towards 0 when open filter drawer
            style={"width": "300px", "flexShrink": 0, "backgroundColor": "green"},
            children="Left menu",
        ),
        html.Div(
            style={"height": "600px", "width": "100%"},
            children=[
                webviz_subsurface_components.WellCompletions(
                    id="well_completions", data=data
                ),
            ],
        ),
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by aprilzhang** [comment]
Thank you @anders-kiaer . I had a look at this example. The style for the second div needs to be changed to style={"height": "600px", "width": "**calc(100% - 300px)**"} so that it takes the width of the left drawer into consideration.
