### ISSUE TITLE
Reduce zoom delta in LayeredMap

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#40]
We are currently using integer only zoom in LayeredMap.
This gives quite large jump in zoom levels when zooming in the view.
It would be useful if the zoom levels could be more flexible.

Per https://leafletjs.com/examples/zoom-levels/ (Fractional zoom) it is possible to have much smaller zoom increments by using the props `zoomDelta` and `zoomSnap`.

`zoomDelta` controls how much the view zooms in when using the buttons, while
`zoomSnap`will snap the zoom to a nearest accepted value.

Perhaps add these as props with a default:
`zoomDelta : 0.25`
`zoomSnap: 0` ?

**Comment by thor85** [comment]
`wheelPxPerZoomLevel` controls zoom delta when using mouse wheel. Higher value is same as lower `ZoomDelta`. Set it to a high value and it will use `zoomSnap`.

**Comment by anders-kiaer** [comment]
Moved to #110 for better overview. Closing this.
