### ISSUE TITLE
Bug: Several issues in `VectorSelector`

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface-components#444]
The `VectorSelector` is currently case-sensitive, whilst `Eclipse` simulation vectors are generally upper case. Making the `VectorSelector`'s search case-insensitive would improve user experience. 

The natural way to go is maybe an optional flag to switch between case-sensitive and insensitive search in the `SmartNodeSelector` in `webviz-core-components`? Added a comment for it in https://github.com/equinor/webviz-core-components/issues/149

**Comment by magnesj** [comment]
I think this issue should be prioritized higher. Candidate for next release?

**Comment by rubenthoms** [comment]
This should be fixed via #626.
