### ISSUE TITLE
Create schemas for input data for Map component

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#487]
Need schema for
- [x] Well trajectories
- [x] Well logs
- [x] Grid layers
- [x] Color tables
- [x] Pie charts
- [x] Fault polygons

- [x] Schema should be validated, and errors should be handled gracefully (ie. no crash, give a helpful warning message)

- [x] Schema validation should be optional

- [ ] Schema should have versions (should be validated by the component)

**Comment by hkfb** [comment]
Check well log validation in the well log viewer. Schema file: [react/src/lib/inputSchema/WellLog.json](https://github.com/equinor/webviz-subsurface-components/commit/eee9cb68a452a22a38b150c172636ee4bf0360e7#diff-553d74a7c516f69a3170f6dd3f0d503ba475f3ca157df434e6f94333f1371f2d)

**Comment by hkfb** [comment]
As the Json well log format is an array at the top level, and we don't have any use cases to modify or extend the format, we can drop versioning on the well log data.

**Comment by shadab-skhan** [comment]
A new issue has been created for schema versioning #1077
