### ISSUE TITLE
Move units to after value?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface-components#513]
This is how it currently is:
![image](https://user-images.githubusercontent.com/31612826/130644161-7e963af9-3b08-471e-9ea0-e46c28253ed1.png)

https://en.wikipedia.org/wiki/International_System_of_Units

**Comment by hkfb** [comment]
@Vladimir-Kokin has this been merged?

**Comment by Vladimir-Kokin** [comment]
Units moved in https://github.com/equinor/webviz-subsurface-components/pull/519
