### ISSUE TITLE
Selecting multiple well trajectories

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#531]
Make lasso based selection of wells

- Either: There should be a callback function prop on the selection layer. When a selection is committed, then the callback should trigger, given the list of selected objects as an argument.
- Or: There should be a react hook that gives the currently selected objects. There could be one hook supplying all selected objects, or there could be more specific hooks, eg. `useSelectedWells`.

Use case: Show statistics for multipe wells

- [x] As a user I like to get a list of well name where any part of trajectory is inside the lasso
(Most useful for horizontal and vertical and deviated wells) 

- [x] Add a callback function to return the selectioned wells information

- [x] Add an example story that prints the names of the selected wells

**Comment by shadab-skhan** [comment]
Check https://turfjs.org/ for finding  wells inside the polygon

**Comment by VincentNevermore** [comment]
closed by task #1254

**Comment by hkfb** [comment]
@Midtveit created #1325 and #1326 for the latter use cases.

**Comment by hkfb** [comment]
@Midtveit created #1332 for the task of selecting by well heads only, as it showed some resistance.
