### ISSUE TITLE
Plot area of intersection between two log curves

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#596]
Aka. Left fill and Right fill

Should be able to plot different colors in negative and positive areas.

Example:

![image](https://user-images.githubusercontent.com/19621822/136949992-f65fd33d-f31b-4634-a3ee-d77a3a899e8f.png)

**Comment by Vladimir-Kokin** [comment]
#635 add usage of videx-wellog 'differential' plot type
