### ISSUE TITLE
Minor updates of `VectorCalculator` based on `SmartNodeSelector` enhancement

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz-subsurface-components#608]
Update `VectorCalculator` based on enhancement/fix in `SmartNodeSelector`

Based on: https://github.com/equinor/webviz-core-components/pull/178 and https://github.com/equinor/webviz-core-components/pull/181

- With update of `SmartNodeSelector` with its suggestion popup placed on top, the `VectorSelector` utilized in `VectorCalculator` can be placed in an max height are or scroll field, as suggestion popup will not trigger scroll area.
- Add usage of "TreeData" and "TreeDataNode" as it is exported?
- Set case-insensitive search
- Set placeholder: "Add new vector..."

**Comment by rubenthoms** [comment]
Consider also adding a dialog asking if the user wants to save changes when switching to a different expression in the list and not having saved changes yet.

**Comment by jorgenherje** [comment]
When external parsing is utilized, the default expression for "New expression" should be parsed/validated? Now it shows valid and is not parsed until editing is started

**Comment by jorgenherje** [comment]
Closed by https://github.com/equinor/webviz-subsurface-components/pull/860
