### ISSUE TITLE
LeafletMap and LayeredMap demos are broken when ran from sandbox

### ISSUE THREAD

**Issue by t0oF** [equinor/webviz-subsurface-components#612]
The colormap and hillshading layers are not displaying anything. The shaders are not loaded any more, since the support for storybook.

How to reproduce:
- checkout the repo
- run `npm install`
- run `npm start`
- select either of LeafletMap or LayeredMap

BTW, though DeckGlMap works in the storybook, it fails like the LeafletMap and LayeredMap when used by a client npm project.

**Comment by hkfb** [comment]
I believe this is working now.

**Comment by t0oF-emr** [comment]
Yes, it's working fine now.
Thanks.
