### ISSUE TITLE
Linked well log views

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#693]
Storybook example: two well log views next to each other

Well log viewer linking:
- [x] TVD hover,
- [x]  TVD range,
- [x]  TVD selection,
- [x]  template,

**Comment by Midtveit** [comment]
The first use case for sync 2 log views are TVD
Link TVD will work for two views with different wells and for two views with same well 
Later we we will se more complex use cases where we link other views with log view
That is to be discussed @HansKallekleiv
