### ISSUE TITLE
Color legend is visible only on 1st view of multi view

### ISSUE THREAD

**Issue by shadab-skhan** [equinor/webviz-subsurface-components#806]
In case of multi view, color legend is visible only on 1st view and not on others. If I use any test div element, it gets rendered on all the views. Looks like absolute positioning issue on ColorTable component.
![image](https://user-images.githubusercontent.com/9147767/153124169-45bcd6c4-144e-4c2c-9605-9aa102bfc2a3.png)

**Comment by shruthirai** [comment]
@shadab-skhan now you can take latest code and check if it works fine since the changes are done in emerson-colortable repo and current code is updated with latest colortable version. 

Also the issue was not with absolute positioning but had to work with something else.

**Comment by shadab-skhan** [comment]
The issue is fixed with @emerson-eps/color-tables version 0.1.21
