### ISSUE TITLE
LayeredMap: Props returning layer coordinates should include layer id

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#84]
The props `polyline_points`, `polygon_points`, `marker_point` returns layer coordinates for both for layers made client side and for overlay layers from props.

Currently only coordinates are returned with no additional layer information.
A layer `id` should be added so that the layer can be identified in Dash.

**Comment by anders-kiaer** [comment]
Closing this as we are creating an entirely new component. This should be takin into account when designing and solving #110.
