### ISSUE TITLE
Callback for readout

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#875]
Add a callback option to the coords prop, for example:

```
"coords": {
    "visible": false,
    "multiPicking": true,
    "pickDepth": 10,
    "callback": (params) => {renderTooltip(params)} 
}
```

- [x] The callback should be optional, and if omitted should do nothing.
- [x] `params` should on hover contain info on cursor position, including
  - [x] x, y coordinates
  - [x] hovered object name
  - [x] hovered MD if well trajectory
  - [x] hovered Log name, value if log curve
  - [x] hovered property value (if grid, property map)
  - [x] hovered depth (if depth surface)

**Comment by shadab-skhan** [comment]
All the information's are provide by onHover and onMouseEvent callbacks of the component.
