### ISSUE TITLE
Display well logs in layeredmap

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#90]
- [ ] Display well logs as color-filled line/area on well trajectory in top-down view.

- [ ] Set colorscale and min/max - (Could be predefined)

- [ ] Show legend

![image](https://user-images.githubusercontent.com/16436291/70794689-86b0e680-1d9e-11ea-9b43-dd9326b88b75.png)

![image](https://user-images.githubusercontent.com/16436291/70794741-ac3df000-1d9e-11ea-8227-ca27f7829683.png)

**Comment by anders-kiaer** [comment]
Moved to #110 for better overview. Closing this.
