### ISSUE TITLE
Extend feature properties for wells

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#916]
Users would like to control the properties of individual wells within a single well layer: color, line width and line style. 

Currently the only available props are the color. the request is to add line width and line style per well\feature.
Please note that currently there is no support for line style option at all and line width can only be controlled in a global per-layer fashion.

**Comment by hkfb** [comment]
@mirisb what is the use case? Do you want to control the style from the back-end via the geojson file or control it via props to the WellsLayer?

**Comment by hkfb** [comment]
Created issue #944 for the remaining use case to set well trajectory line width.
