### ISSUE TITLE
Improved bounds specification for maps

### ISSUE THREAD

**Issue by hkfb** [equinor/webviz-subsurface-components#924]
- [x] remove the global bounds, calculate automatically from union of all layers (include rotation)
- [x] should not move camera if bounds are changed
- [x] replace layer `bounds` (for colorMap, hillshading, Map3DLayer) with origin (x, y), (xinc, yinc) **or** (x-extent, y-extent). 
- [x] Should be backwards compatible (grace period)
- [x] Coordinate system handedness (left/right-handed)

Nice to have:
- [x] Rotation around same corner as Resqml
- [x] Same rotation direction as Resqml

**Comment by hkfb** [comment]
Need to also handle different coordinate systems (right/left-handed)

**Comment by hkfb** [comment]
Suggestions from Views team:
- Arbitrary rotation point

**Comment by nilscb** [comment]
"Bounds" are changed to "Frame" property for MapLayer and Map3DLayer but not for colormap and hillshading layer as "bounds" are more suited for them, The given inout image already contains number of pixels and width height. Setting to "Done"
