### ISSUE TITLE
When I provide lineWidthScale through resources then when opening the props for the layer I don't see the value

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#955]
In layer definition I provide the width of the trajectory line using resources: 
`{
  "@@type": "WellsLayer",
  id: "wells-layer",
  lineWidthScale: "@@#resources.lineWidthScale",
...
}`
The trajectories are being rendered correctly however, when I open the wells properties the value for trajectory line width is empty. 
![image](https://user-images.githubusercontent.com/18436935/165740720-5d351e88-9f20-4fd8-b25c-2a74d5b4be1d.png)
It is possible to enter a value manually and then edit it with the arrows.

**Comment by hkfb** [comment]
@mirisb do you plan to use the toolbar in your project? We are considering deprecating the toolbar, as we don't have any important use cases in other projects.

**Comment by mirisb** [comment]
I would like to be able to control all visibility aspects through props. Right now the tool bars in the webviz implementation are nice to have but ultimately props would need to be controlled from outside by the app. We should have a discussion about it.

**Comment by hkfb** [comment]
We plan to deprecate the toolbar, so we will not fix this, sorry :)

**Comment by mirisb** [comment]
will you deprecate everything? including layer display control and properties?
